In [275]:
# To compare the difference of the years, seperate the data according to years
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import Imputer
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn import tree
import pydotplus
import statsmodels.api as sm
from scipy import stats

# Import all data

In [276]:
CM_2013 = pd.read_csv("CM_2013.csv", header = 0)
CM_2015 = pd.read_csv("CM_2015.csv", header = 0)
CM_2011 = pd.read_csv("CM_2011.csv", header = 0)

## See what the dataset looks like

In [229]:
CM_2011.head()

,NPA,Hispanic_Latino_2011,All_Other_Races_2011,Asian_Population_2011,Black_Population_2011,White_Population_2011,Older_Adult_Population_2011,Youth_Population_2011,Age_of_Residents_2011,Population_Density_2011,...,Foreclosed_Units_2011,Housing_Violations_2011,Housing_Violations_Total_2011,Street_Connectivity_2011,Transit_Proximity_2011,Transit_Proximate_Units_2011,Violent_Crime_Rate_2011,Property_Crime_Rate_2011,Violent_Crime_Rate_Log2_2011,Property_Crime_Rate_Log2_2011
0,2,9.2,2.8,1.5,33.7,52.8,8.0,14.0,32,5,...,7.0,0.65,7.0,1.17,100.0,1082.0,9.3,120.2,3.217231,6.909293
1,3,2.1,1.9,2.1,10.2,83.7,10.0,13.0,31,6,...,24.0,1.26,55.0,1.55,100.0,4468.0,2.0,77.4,1.000000,6.274262
2,4,0.9,0.7,3.5,1.6,93.3,24.0,27.0,43,3,...,1.0,0.25,1.0,1.17,100.0,401.0,0.0,13.0,0.000000,3.700440
3,5,2.7,3.5,2.0,83.3,8.6,4.0,36.0,29,4,...,11.0,7.83,26.0,1.19,100.0,332.0,21.6,73.0,4.432959,6.189825
4,6,3.8,1.7,1.1,78.6,14.7,9.0,18.0,38,4,...,7.0,4.24,35.0,1.30,100.0,825.0,27.5,92.2,4.781360,6.526695

In [75]:
CM_2013.head()

,NPA,Vacant_Land_2013,Vacant_Land_Area_2013,Commercial_Construction_2013,Commercial_Construction_Permitted_Units_2013,Commercial_Size_2013,Commercial_Size_Total_2013,Commercial_Building_Age_2013,Impervious_Surface_2013,Impervious_Surface_Area_2013,...,Foreclosed_Units_2013,Housing_Violations_2013,Housing_Violations_Total_2013,Street_Connectivity_2013,Transit_Proximity_2013,Transit_Proximate_Units_2013,Violent_Crime_Rate_2013,Property_Crime_Rate_2013,Violent_Crime_Rate_Log2_2013,Property_Crime_Rate_Log2_2013
0,2,4.3,18,2.19,9,13630.0,545219.0,49.0,23.1,95,...,6.0,1.20,13.0,1.15,100.0,1081.0,6.9,32.8,2.786596,5.035624
1,3,2.8,33,12.11,140,27466.0,10382242.0,62.0,36.9,427,...,17.0,0.42,20.0,1.55,100.0,4746.0,2.2,59.5,1.137504,5.894818
2,4,5.1,17,0.30,1,4398.0,4398.0,30.0,19.7,65,...,0.0,0.00,0.0,1.17,100.0,402.0,0.0,9.4,0.000000,3.232661
3,5,21.4,36,0.60,1,28847.0,490401.0,53.0,25.7,43,...,1.0,9.42,31.0,1.19,100.0,329.0,24.9,51.1,4.638074,5.675251
4,6,7.7,31,1.74,7,11716.0,808387.0,47.0,25.0,101,...,9.0,6.59,54.0,1.30,100.0,820.0,31.0,94.1,4.954196,6.556123

In [76]:
CM_2015.head()

,NPA,Vacant_Land_2015,Vacant_Land_Area_2015,Commercial_Construction_2015,Commercial_Construction_Permitted_Units_2015,Commercial_Size_2015,Commercial_Size_Total_2015,Commercial_Building_Age_2015,Impervious_Surface_2015,Impervious_Surface_Area_2015,...,Foreclosed_Units_2015,Housing_Violations_2015,Housing_Violations_Total_2015,Street_Connectivity_2015,Transit_Proximity_2015,Transit_Proximate_Units_2015,Violent_Crime_Rate_2015,Property_Crime_Rate_2015,Violent_Crime_Rate_Log2_2015,Property_Crime_Rate_Log2_2015
0,2,4.3,18,12.16,50,12670.0,456137.0,51.0,22.1,91,...,7.0,0.93,10.0,1.20,100.0,1079.0,4.5,31.1,2.169925,4.958843
1,3,2.5,29,8.56,99,28152.0,10500735.0,63.0,37.3,431,...,4.0,0.17,8.0,1.50,100.0,4752.0,2.1,61.1,1.070389,5.933100
2,4,5.1,17,0.00,0,4398.0,4398.0,32.0,19.7,65,...,1.0,0.00,0.0,1.17,94.0,381.0,0.9,19.5,0.900000,4.285402
3,5,21.4,36,6.58,11,28777.0,489205.0,55.0,22.1,37,...,4.0,19.94,66.0,1.16,100.0,331.0,18.8,67.1,4.232661,6.068241
4,6,7.7,31,1.49,6,11740.0,810086.0,50.0,25.0,101,...,6.0,6.61,54.0,1.30,100.0,817.0,24.4,100.9,4.608809,6.656782

# For Violate crime

## pick up 10 most inflential fetures

### These are: Housing_Violations, Housing_Size, Transit_Proximity, Impervious_Surface, Street_Connectivity, Commercial_Building_Age,Housing_Age, Residential_Renovation , Transit_Proximate_Units, Foreclosures

In [277]:
data_x_2011 = CM_2011[['Housing_Violations_2011','Housing_Size_2011', 'Transit_Proximity_2011',
                       'Impervious_Surface_2011', 'Street_Connectivity_2011', 'Commercial_Building_Age_2011',
                       'Housing_Age_2011', 'Residential_Renovation_2011' , 'Transit_Proximate_Units_2011', 
                       'Foreclosures_2011' ]]
data_x_2013 = CM_2013[['Housing_Violations_2013','Housing_Size_2013', 'Transit_Proximity_2013',
                       'Impervious_Surface_2013', 'Street_Connectivity_2013', 'Commercial_Building_Age_2013',
                       'Housing_Age_2013', 'Residential_Renovation_2013' , 'Transit_Proximate_Units_2013', 
                       'Foreclosures_2013' ]]
data_x_2015 = CM_2015[['Housing_Violations_2015','Housing_Size_2015', 'Transit_Proximity_2015',
                       'Impervious_Surface_2015', 'Street_Connectivity_2015', 'Commercial_Building_Age_2015',
                       'Housing_Age_2015', 'Residential_Renovation_2015' , 'Transit_Proximate_Units_2015', 
                       'Foreclosures_2015' ]]

In [78]:
data_x_2011.head()

,Housing_Violations_2011,Housing_Size_2011,Transit_Proximity_2011,Impervious_Surface_2011,Street_Connectivity_2011,Commercial_Building_Age_2011,Housing_Age_2011,Residential_Renovation_2011,Transit_Proximate_Units_2011,Foreclosures_2011
0,0.65,1446.0,100.0,NaN,1.17,47.0,64.0,2.67,1082.0,1.1
1,1.26,2033.0,100.0,23.3,1.55,60.0,68.0,6.66,4468.0,0.7
2,0.25,3660.0,100.0,36.9,1.17,28.0,40.0,8.20,401.0,0.3
3,7.83,1041.0,100.0,19.7,1.19,52.0,55.0,1.20,332.0,6.0
4,4.24,1073.0,100.0,22.1,1.30,47.0,63.0,1.49,825.0,1.2

In [278]:
y_2011 = CM_2011[['Violent_Crime_Rate_2011','Property_Crime_Rate_2011']]
y_2013 = CM_2013[['Violent_Crime_Rate_2013','Property_Crime_Rate_2013']]
y_2015 = CM_2015[['Violent_Crime_Rate_2015','Property_Crime_Rate_2015']]

In [80]:
y_2011.head()

   Violent_Crime_Rate_2011  Property_Crime_Rate_2011
0                      9.3                     120.2
1                      2.0                      77.4
2                      0.0                      13.0
3                     21.6                      73.0
4                     27.5                      92.2

## deal with missing values

### assign them as mean value

In [279]:
imputerx_2011 = Imputer(strategy='mean')
data_x_2011_imputed = imputerx_2011.fit_transform(data_x_2011)
imputery_2011 = Imputer(strategy='mean')
y_2011_imputed = imputery_2011.fit_transform(y_2011)

imputerx_2013 = Imputer(strategy='mean')
data_x_2013_imputed = imputerx_2013.fit_transform(data_x_2013)
imputery_2013 = Imputer(strategy='mean')
y_2013_imputed = imputery_2013.fit_transform(y_2013)

imputerx_2015 = Imputer(strategy='mean')
data_x_2015_imputed = imputerx_2015.fit_transform(data_x_2015)
imputery_2015 = Imputer(strategy='mean')
y_2015_imputed = imputery_2015.fit_transform(y_2015)

In [87]:
y_2015_imputed[:,0]

array([  4.5       ,   2.1       ,   0.9       ,  18.8       ,
        24.4       ,   0.        ,   0.5       ,   3.3       ,
        11.5       ,   0.8       ,  11.6       ,   2.8       ,
         1.9       ,   0.        ,   3.6       ,   5.6       ,
         1.8       ,   0.        ,   0.        ,   7.4       ,
         7.3       ,   0.        ,   1.8       ,   0.7       ,
         1.        ,   0.7       ,   1.7       ,   1.6       ,
        13.4       ,   0.6       ,   3.        ,   1.5       ,
         4.6       ,   5.3       ,   0.7       ,  14.1       ,
         2.1       ,   1.8       ,   8.2       ,   1.9       ,
         0.        ,   0.        ,   0.        ,   0.9       ,
         1.6       ,   0.        ,   4.9       ,   1.9       ,
        10.7       ,  13.        ,  14.4       ,  13.8       ,
         4.        ,   0.        ,  12.9       ,   3.1       ,
         7.3       ,   6.4       ,   4.8       ,   5.        ,
         0.        ,   4.2       ,   1.4       ,   4.        ,
         6.        ,   1.2       ,   0.        ,  21.1       ,
         6.7       ,   4.        ,   4.6       ,   0.9       ,
         1.        ,   0.9       ,   0.8       ,   3.4       ,
        10.4       ,   0.5       ,   0.        ,   1.6       ,
         0.        ,   4.3       ,  19.2       ,   5.1       ,
         6.        ,  20.6       ,   2.6       ,  17.        ,
         0.8       ,   1.3       ,   3.7       ,   8.2       ,
         1.2       ,   2.1       ,   1.6       ,   1.5       ,
         2.        ,  13.3       ,   7.3       ,   6.1       ,
        17.2       ,   1.5       ,   9.3       ,   2.2       ,
         7.        ,   1.6       ,   2.7       ,   1.9       ,
         2.        ,   3.5       ,  10.4       ,   0.2       ,
         4.89004425,   1.8       ,   0.        ,   8.9       ,
        17.2       ,   6.2       ,   4.89004425,   9.1       ,
        22.7       ,   8.9       ,   9.3       ,   5.1       ,
         8.3       ,   0.        ,   2.2       ,   0.        ,
         1.9       ,   0.        ,   4.8       ,   9.4       ,
         1.        ,   5.8       ,  41.8       ,   9.6       ,
         8.8       ,  28.1       ,   4.9       ,   0.        ,
         6.2       ,   5.3       ,   3.8       ,   6.5       ,
         0.8       ,   0.        ,   3.3       ,   0.3       ,
         2.5       ,   1.5       ,   0.3       ,   0.7       ,
         1.7       ,  44.2       ,   6.8       ,  14.7       ,
        10.        ,   2.3       ,   5.7       ,   5.5       ,
        13.1       ,   7.7       ,  14.2       ,  11.1       ,
         5.7       ,   0.5       ,   0.        ,   1.1       ,
         1.        ,  13.1       ,   2.9       ,   0.        ,
         0.        ,   0.5       ,   2.9       ,   0.        ,
         4.2       ,   0.7       ,  20.5       ,   3.5       ,
         0.        ,   5.7       ,   4.9       ,   0.        ,
         0.        ,   2.9       ,   7.7       ,   1.3       ,
         3.8       ,   0.        ,   0.7       ,   1.4       ,
         6.4       ,   2.7       ,   1.8       ,  20.5       ,
        16.6       ,   0.        ,   5.6       ,   0.5       ,
         0.7       ,   0.        ,   0.        ,   0.8       ,
         1.        ,   2.5       ,   1.6       ,   2.4       ,
        12.2       ,   1.9       ,   1.2       ,   0.        ,
         0.        ,   1.9       ,   8.9       ,   5.7       ,
         2.2       ,   0.        ,  11.9       ,   1.3       ,
         1.5       ,   0.        ,   2.        ,   5.5       ,
         9.3       ,   2.        ,   1.8       ,   0.8       ,
         1.2       ,   8.4       ,   1.        ,   0.9       ,
         7.4       ,   5.9       ,   6.1       ,   0.5       ,
         0.6       ,   0.        ,   1.        ,   9.8       ,
         2.9       ,   8.7       ,   7.2       ,  22.2       ,
         1.2       ,   1.7       ,   0.        ,   0.5       ,
         5.5       ,   0.4       ,   0.3       ,   0.3       ,
         6.2       ,   5.6       ,   5.6       ,   1.3       ,
         0.3       ,   0.        ,   2.4       ,   0.        ,
         2.4       ,   0.4       ,   1.7       ,   1.1       ,
         8.7       ,   5.        ,   3.5       ,   2.1       ,
         4.8       ,   3.3       ,   0.5       ,   0.6       ,
         2.5       ,   0.        ,   6.3       ,   2.8       ,
         0.        ,   2.6       ,   1.        ,   4.89004425,
        26.5       ,   8.3       ,   1.3       ,   1.9       ,
        41.7       ,  10.9       ,   7.        ,  17.        ,
        35.9       ,  10.6       ,   0.6       ,   0.        ,
         4.89004425,   2.6       ,   4.89004425,   0.4       ,
         0.7       ,   1.1       ,  17.        ,   6.7       ,
         9.8       ,   2.4       ,   0.8       ,   0.        ,
         0.9       ,  16.4       ,  10.7       ,   1.2       ,
         5.7       ,  13.5       ,   7.5       ,  16.3       ,
         1.2       ,   1.5       ,   0.        ,  18.6       ,
         0.8       ,   5.        ,   1.2       ,   4.7       ,
         8.3       ,   8.8       ,  27.3       ,   2.9       ,
         3.7       ,  14.2       ,   2.3       ,   4.7       ,
         0.        ,   0.3       ,   0.2       ,   0.5       ,
        11.3       ,   3.2       ,   7.7       ,  14.        ,
        74.5       ,   8.7       ,   7.3       ,   2.1       ,
         7.        ,  15.1       ,   4.1       ,   1.5       ,
         0.        ,   1.7       ,   0.4       ,   0.4       ,
         0.6       ,   1.4       ,   0.6       ,   0.7       ,
         2.2       ,   0.4       ,   2.5       ,  29.8       ,
         9.1       ,  19.9       ,   0.        ,   5.9       ,
        16.3       ,   2.5       ,   4.89004425,  24.5       ,
        19.9       ,  14.4       ,   0.4       ,   0.        ,
        23.7       ,   0.        ,   1.5       ,   1.1       ,
         0.7       ,   0.2       ,   0.        ,   3.2       ,
         8.9       ,   4.9       ,   8.5       ,  17.5       ,
         8.2       ,  24.9       ,  10.7       ,   4.9       ,
         0.7       ,   0.4       ,   0.6       ,   0.5       ,
         1.4       ,   3.2       ,   0.7       ,   0.        ,
         0.        ,   1.5       ,   1.6       ,   5.        ,
         2.5       ,   0.5       ,   4.8       ,   0.9       ,
         0.9       ,   0.5       ,   0.4       ,   0.        ,
         0.6       ,   0.        ,   0.        ,   0.        ,
         1.2       ,   0.        ,   0.3       ,   0.7       ,
         1.1       ,   1.2       ,   3.8       ,   1.9       ,
         0.        ,   0.8       ,   2.5       ,   3.3       ,
         4.89004425,   0.        ,   4.6       ,   0.        ,
         0.6       ,   3.3       ,   0.6       ,   3.1       ,
         1.        ,   2.        ,   4.89004425,   4.89004425,
         0.3       ,   0.7       ,   0.8       ,   2.9       ,
         0.4       ,   0.5       ,   0.3       ,   0.6       ,
         4.89004425,   1.3       ,   0.        ,   5.5       ,
         1.        ,   0.9       ,   2.9       ,   5.7       ,
         0.5       ,   5.        ,   1.7       ,   0.8       ,
         1.2       ,   0.9       ,   0.        ,   0.5       ,
         0.        ,   1.4       ,   0.        ,   3.5       ,
         0.8       ,   0.        ])

## Standardize

In [294]:
from sklearn import preprocessing
data_x_2011_imputed_stan = preprocessing.scale(data_x_2011_imputed)

In [295]:
data_x_2013_imputed_stan = preprocessing.scale(data_x_2013_imputed)
data_x_2015_imputed_stan = preprocessing.scale(data_x_2015_imputed)
y_2011_imputed_stan = preprocessing.scale(y_2011_imputed)
y_2013_imputed_stan = preprocessing.scale(y_2013_imputed)
y_2015_imputed_stan = preprocessing.scale(y_2015_imputed)

In [296]:
linRe_2011 = LinearRegression()
linRe_2011.fit(data_x_2011_imputed_stan,y_2011_imputed_stan[:,0])

linRe_2013 = LinearRegression()
linRe_2013.fit(data_x_2013_imputed_stan,y_2013_imputed_stan[:,0])

linRe_2015 = LinearRegression()
linRe_2015.fit(data_x_2015_imputed_stan,y_2015_imputed_stan[:,0])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [297]:
linRe_2011.coef_

array([ 0.11610529, -0.08952595,  0.30157875,  0.04048891,  0.2887805 ,
        0.05919466,  0.11628773, -0.1486921 , -0.30143563,  0.03880012])

In [298]:
linRe_2013.coef_

array([ 0.27526485, -0.21656239,  0.09995098,  0.2717513 ,  0.1873998 ,
        0.07526968,  0.03621494, -0.05917136, -0.21486877, -0.01953285])

In [299]:
linRe_2015.coef_

array([ 0.27789419, -0.11685581,  0.20259289,  0.18970104,  0.22475831,
        0.09709919,  0.06935798, -0.14508292, -0.26915785,  0.0773897 ])

## fit model

In [89]:
linRe_2011 = LinearRegression()
linRe_2011.fit(data_x_2011_imputed,y_2011_imputed[:,0])

linRe_2013 = LinearRegression()
linRe_2013.fit(data_x_2013_imputed,y_2013_imputed[:,0])

linRe_2015 = LinearRegression()
linRe_2015.fit(data_x_2015_imputed,y_2015_imputed[:,0])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [282]:
p_2011 = sm.OLS(y_2011_imputed[:,0],data_x_2011_imputed)
p_2011_2 = p_2011.fit()
p_2013 = sm.OLS(y_2013_imputed[:,0],data_x_2013_imputed)
p_2013_2 = p_2013.fit()
p_2015 = sm.OLS(y_2015_imputed[:,0],data_x_2015_imputed)
p_2015_2 = p_2015.fit()

In [290]:
print p_2011_2.params

[  8.21127647e-01  -2.58081544e-03   4.85076680e-02   2.34877919e-02
   5.25287279e+00   2.48696055e-02   8.58160994e-02  -5.22202725e-01
  -3.68095574e-03  -1.44571826e-01]

In [291]:
print p_2013_2.params

[  1.31709982e+00  -3.36138654e-03   1.49165650e-02   2.14312035e-01
   5.44919984e+00   3.99772693e-02   9.35060719e-03  -8.54441873e-02
  -2.62917832e-03  -6.30279918e-01]

In [292]:
print p_2015_2.params

[  1.04514504e+00  -2.50703897e-03   3.02902128e-02   1.31913687e-01
   3.63776689e+00   4.63695882e-02   2.36521819e-02  -1.98293872e-01
  -2.69303055e-03   2.39854544e-02]

## output the coef in 2011

In [90]:
linRe_2011.coef_

array([  7.63298056e-01,  -1.07401544e-03,   6.63976359e-02,
         3.61439009e-02,   2.34716091e+01,   3.86828189e-02,
         6.29871757e-02,  -5.82625742e-01,  -4.70618010e-03,
         2.91573195e-01])

In [91]:
linRe_2013.coef_

array([  1.32664348e+00,  -2.40804496e-03,   2.07797597e-02,
         2.21400876e-01,   1.26851995e+01,   4.54555721e-02,
         1.83788372e-02,  -1.31454244e-01,  -3.06534654e-03,
        -1.85177515e-01])

In [92]:
linRe_2015.coef_

array([  1.07424205e+00,  -1.16339847e-03,   3.75770775e-02,
         1.40613168e-01,   1.57929741e+01,   5.26532297e-02,
         3.16605949e-02,  -2.98078744e-01,  -3.39115800e-03,
         5.93620617e-01])

# For Property Crime

## select 10 most influential features
### They are: Impervious_Surface, Transit_Proximity, Impervious_Surface_Area, Pharmacy_Proximity, Street_Connectivity, Housing_Age, Foreclosures, Vacant_Land, Residential_Renovation, Commercial_Size

In [283]:
data_x_2011_pc = CM_2011[['Impervious_Surface_2011', 'Transit_Proximity_2011', 'Impervious_Surface_Area_2011', 
                          'Pharmacy_Proximity_2011', 'Street_Connectivity_2011', 'Housing_Age_2011',
                          'Foreclosures_2011', 'Vacant_Land_2011', 'Residential_Renovation_2011',
                          'Commercial_Size_2011' ]]
data_x_2013_pc = CM_2013[['Impervious_Surface_2013', 'Transit_Proximity_2013', 'Impervious_Surface_Area_2013',
                          'Pharmacy_Proximity_2013', 'Street_Connectivity_2013', 'Housing_Age_2013', 
                          'Foreclosures_2013', 'Vacant_Land_2013', 'Residential_Renovation_2013',
                          'Commercial_Size_2013'  ]]
data_x_2015_pc = CM_2015[['Impervious_Surface_2015', 'Transit_Proximity_2015', 'Impervious_Surface_Area_2015', 
                          'Pharmacy_Proximity_2015', 'Street_Connectivity_2015', 'Housing_Age_2015', 
                          'Foreclosures_2015', 'Vacant_Land_2015', 'Residential_Renovation_2015',
                          'Commercial_Size_2015'  ]]

In [94]:
data_x_2011_pc.head()

,Impervious_Surface_2011,Transit_Proximity_2011,Impervious_Surface_Area_2011,Pharmacy_Proximity_2011,Street_Connectivity_2011,Housing_Age_2011,Foreclosures_2011,Vacant_Land_2011,Residential_Renovation_2011,Commercial_Size_2011
0,NaN,100.0,96,20.0,1.17,64.0,1.1,4.3,2.67,13336.0
1,23.3,100.0,427,95.0,1.55,68.0,0.7,3.2,6.66,24289.0
2,36.9,100.0,65,15.0,1.17,40.0,0.3,5.1,8.20,4398.0
3,19.7,100.0,37,9.0,1.19,55.0,6.0,21.4,1.20,27561.0
4,22.1,100.0,103,87.0,1.30,63.0,1.2,7.7,1.49,11596.0

In [284]:
imputerx_2011 = Imputer(strategy='mean')
data_x_2011_pc_imputed = imputerx_2011.fit_transform(data_x_2011_pc)


imputerx_2013 = Imputer(strategy='mean')
data_x_2013_pc_imputed = imputerx_2013.fit_transform(data_x_2013_pc)


imputerx_2015 = Imputer(strategy='mean')
data_x_2015_pc_imputed = imputerx_2015.fit_transform(data_x_2015_pc)

In [96]:
data_x_2011_pc_imputed

array([[  1.82765727e+01,   1.00000000e+02,   9.60000000e+01, ...,
          4.30000000e+00,   2.67000000e+00,   1.33360000e+04],
       [  2.33000000e+01,   1.00000000e+02,   4.27000000e+02, ...,
          3.20000000e+00,   6.66000000e+00,   2.42890000e+04],
       [  3.69000000e+01,   1.00000000e+02,   6.50000000e+01, ...,
          5.10000000e+00,   8.20000000e+00,   4.39800000e+03],
       ...,
       [  1.45000000e+01,   1.00000000e+02,   9.40000000e+01, ...,
          2.13000000e+01,   2.47000000e+00,   1.17210000e+04],
       [  1.93000000e+01,   6.70000000e+01,   1.09000000e+02, ...,
          7.40000000e+00,   2.19000000e+00,   1.75120000e+04],
       [  2.17000000e+01,   4.60000000e+01,   8.90000000e+01, ...,
          1.16000000e+01,   3.49000000e+00,   7.59300000e+03]])

## standardize

In [300]:
data_x_2011_pc_imputed_stan = preprocessing.scale(data_x_2011_pc_imputed)
data_x_2013_pc_imputed_stan = preprocessing.scale(data_x_2013_pc_imputed)
data_x_2015_pc_imputed_stan = preprocessing.scale(data_x_2015_pc_imputed)

In [301]:
linRe_2011_pc = LinearRegression()
linRe_2011_pc.fit(data_x_2011_pc_imputed_stan,y_2011_imputed_stan[:,1])

linRe_2013_pc = LinearRegression()
linRe_2013_pc.fit(data_x_2013_pc_imputed_stan,y_2013_imputed_stan[:,1])

linRe_2015_pc = LinearRegression()
linRe_2015_pc.fit(data_x_2015_pc_imputed_stan,y_2015_imputed_stan[:,1])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [302]:
linRe_2011_pc.coef_

array([ 0.00797949,  0.1518102 ,  0.02991958,  0.02952287,  0.17956414,
        0.13938885, -0.03321725,  0.16898463, -0.13607954,  0.01070039])

In [303]:
linRe_2013_pc.coef_

array([ 0.24498981,  0.08950255,  0.09488647,  0.02897577,  0.25986838,
        0.07342755, -0.00880692,  0.14492804, -0.13679487,  0.03035153])

In [304]:
linRe_2015_pc.coef_

array([ 0.26127019,  0.01892548,  0.07048507,  0.05609003,  0.21026634,
        0.16136623,  0.09358349,  0.14299629, -0.14452956,  0.04788109])

## fit model

In [97]:
linRe_2011_pc = LinearRegression()
linRe_2011_pc.fit(data_x_2011_pc_imputed,y_2011_imputed[:,1])

linRe_2013_pc = LinearRegression()
linRe_2013_pc.fit(data_x_2013_pc_imputed,y_2013_imputed[:,1])

linRe_2015_pc = LinearRegression()
linRe_2015_pc.fit(data_x_2015_pc_imputed,y_2015_imputed[:,1])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [285]:
p_2011_pc = sm.OLS(y_2011_imputed[:,1],data_x_2011_pc_imputed)
p_2011_2_pc = p_2011_pc.fit()
p_2013_pc = sm.OLS(y_2013_imputed[:,1],data_x_2013_pc_imputed)
p_2013_2_pc = p_2013_pc.fit()
p_2015_pc = sm.OLS(y_2015_imputed[:,1],data_x_2015_pc_imputed)
p_2015_2_pc = p_2015_pc.fit()

In [286]:
print p_2015_2_pc.pvalues

[  2.89941872e-04   4.66304532e-01   1.30198503e-02   1.41355777e-01
   4.69663247e-04   2.95074908e-05   2.40409001e-01   1.89929598e-03
   1.72749953e-02   1.60050482e-01]

In [289]:
print p_2011_2_pc.params

[ -1.25132245e-01   3.55220529e-01   6.18858087e-02   1.50030523e-01
  -2.48522369e+01   1.57206823e+00  -5.19824396e+00   1.59495010e+00
  -7.72400122e+00   4.10017736e-05]

In [288]:
print p_2013_2_pc.params

[  1.17082429e+00   1.52992313e-01   8.10468480e-02   1.08346039e-01
  -1.89191185e+01   4.95717882e-01  -3.89837123e+00   8.15561136e-01
  -1.95453875e+00   4.85956562e-05]

In [287]:
print p_2015_2_pc.params

[  1.33619083e+00   6.00094066e-02   6.20349126e-02   1.28531089e-01
  -3.32793818e+01   7.97373352e-01   3.12205984e+00   7.56596527e-01
  -1.79168288e+00   5.41625749e-05]

In [98]:
linRe_2011_pc.coef_

array([  9.16797051e-02,   4.30181874e-01,   3.66806072e-02,
         1.03672756e-01,   1.87842515e+02,   9.71729889e-01,
        -3.21275339e+00,   1.61494855e+00,  -6.86268199e+00,
         1.99126857e-05])

In [99]:
linRe_2013_pc.coef_

array([  1.50415711e+00,   1.40225283e-01,   5.93305932e-02,
         5.51514245e-02,   1.32562009e+02,   2.80819190e-01,
        -6.29193367e-01,   7.52416800e-01,  -2.29018367e+00,
         2.86593695e-05])

In [100]:
linRe_2015_pc.coef_

array([  1.48704970e+00,   2.69541051e-02,   3.93442696e-02,
         9.71786285e-02,   1.13448103e+02,   5.65606766e-01,
         5.51193881e+00,   6.58812460e-01,  -2.28008330e+00,
         4.12471214e-05])

# ADD DEMOGRAPHICS

## Decision Tree for 3 years

### Deal with missing value first

In [231]:
imputer = Imputer(strategy='mean')
CM_2011_imputed = pd.DataFrame(imputer.fit_transform(CM_2011))

CM_2013_imputed = pd.DataFrame(imputer.fit_transform(CM_2013))

CM_2015_imputed = pd.DataFrame(imputer.fit_transform(CM_2015))

In [232]:
CM_2011_imputed.head()

,0,1,2,3,4,5,6,7,8,9,...,34,35,36,37,38,39,40,41,42,43
0,2.0,9.2,2.8,1.5,33.7,52.8,8.0,14.0,32.0,5.0,...,7.0,0.65,7.0,1.17,100.0,1082.0,9.3,120.2,3.217231,6.909293
1,3.0,2.1,1.9,2.1,10.2,83.7,10.0,13.0,31.0,6.0,...,24.0,1.26,55.0,1.55,100.0,4468.0,2.0,77.4,1.000000,6.274262
2,4.0,0.9,0.7,3.5,1.6,93.3,24.0,27.0,43.0,3.0,...,1.0,0.25,1.0,1.17,100.0,401.0,0.0,13.0,0.000000,3.700440
3,5.0,2.7,3.5,2.0,83.3,8.6,4.0,36.0,29.0,4.0,...,11.0,7.83,26.0,1.19,100.0,332.0,21.6,73.0,4.432959,6.189825
4,6.0,3.8,1.7,1.1,78.6,14.7,9.0,18.0,38.0,4.0,...,7.0,4.24,35.0,1.30,100.0,825.0,27.5,92.2,4.781360,6.526695

In [156]:
CM_2013_imputed.head()

,0,1,2,3,4,5,6,7,8,9,...,34,35,36,37,38,39,40,41,42,43
0,2.0,9.2,2.8,1.5,33.7,52.8,8.0,14.0,34.0,5.0,...,6.0,1.20,13.0,1.15,100.0,1081.0,6.9,32.8,2.786596,5.035624
1,3.0,2.1,1.9,2.1,10.2,83.7,10.0,13.0,33.0,7.0,...,17.0,0.42,20.0,1.55,100.0,4746.0,2.2,59.5,1.137504,5.894818
2,4.0,0.9,0.7,3.5,1.6,93.3,24.0,27.0,45.0,3.0,...,0.0,0.00,0.0,1.17,100.0,402.0,0.0,9.4,0.000000,3.232661
3,5.0,2.7,3.5,2.0,83.3,8.6,4.0,36.0,31.0,5.0,...,1.0,9.42,31.0,1.19,100.0,329.0,24.9,51.1,4.638074,5.675251
4,6.0,3.8,1.7,1.1,78.6,14.7,9.0,18.0,40.0,4.0,...,9.0,6.59,54.0,1.30,100.0,820.0,31.0,94.1,4.954196,6.556123

In [157]:
CM_2015_imputed.head()

,0,1,2,3,4,5,6,7,8,9,...,34,35,36,37,38,39,40,41,42,43
0,2.0,9.2,2.8,1.5,33.7,52.8,8.0,14.0,36.0,5.0,...,7.0,0.93,10.0,1.20,100.0,1079.0,4.5,31.1,2.169925,4.958843
1,3.0,2.1,1.9,2.1,10.2,83.7,10.0,13.0,35.0,7.0,...,4.0,0.17,8.0,1.50,100.0,4752.0,2.1,61.1,1.070389,5.933100
2,4.0,0.9,0.7,3.5,1.6,93.3,24.0,27.0,47.0,3.0,...,1.0,0.00,0.0,1.17,94.0,381.0,0.9,19.5,0.900000,4.285402
3,5.0,2.7,3.5,2.0,83.3,8.6,4.0,36.0,33.0,4.0,...,4.0,19.94,66.0,1.16,100.0,331.0,18.8,67.1,4.232661,6.068241
4,6.0,3.8,1.7,1.1,78.6,14.7,9.0,18.0,42.0,4.0,...,6.0,6.61,54.0,1.30,100.0,817.0,24.4,100.9,4.608809,6.656782

### Define feature dictionary

In [233]:
Features_dic_2011 = {'NPA':0, 'Hispanic_Latino_2011': 1,'All_Other_Races_2011': 2,
                     'Asian_Population_2011':3, 'Black_Population_2011': 4,'White_Population_2011': 5,
                     'Older_Adult_Population_2011':6, 'Youth_Population_2011':7, 'Age_of_Residents_2011':8, 
                    'Population_Density_2011':9, 'Vacant_Land_2011':10, 
                     'Vacant_Land_Area_2011':11, 'Commercial_Construction_2011':12, 
                     'Commercial_Construction_Permitted_Units_2011':13, 'Commercial_Size_2011':14,
                     'Commercial_Size_Total_2011':15,'Commercial_Building_Age_2011':16,
                     'Impervious_Surface_2011':17,'Impervious_Surface_Area_2011':18, 'Adopt_a_Stream_2011':19,
                     'Adopt_a_Stream_Length_2011':20, 'Pharmacy_Proximity_2011':21,
                     'Pharmacy_Proximate_Units_2011':22,'Housing_Density_2011':23,'Housing_Units_2011':24,
                     'Single_Family_Housing_2011':25, 'Single_Family_Units_2011':26,
                     'Housing_Size_2011':27, 'Housing_Age_2011':28,'New_Residential_2011':29,
                     'New_Residential_Permit_Units_2011':30,'Residential_Renovation_2011':31,
                     'Residential_Renovation_Permit_Units_2011':32,'Foreclosures_2011':33,
                     'Foreclosed_Units_2011':34,'Housing_Violations_2011':35,
                     'Housing_Violations_Total_2011':36,'Street_Connectivity_2011':37,'Transit_Proximity_2011':38,
                     'Transit_Proximate_Units_2011':39,'Violent_Crime_Rate_2011':40,'Property_Crime_Rate_2011':41,
                     'Violent_Crime_Rate_Log2_2011':42,'Property_Crime_Rate_Log2_2011':43,
                     'Violent_Crime_Rate_Class_2011':44,'Property_Crime_Rate_Class_2011':45 }

In [159]:
Features_dic_2013 = {'NPA':0, 'Hispanic_Latino_2013': 1,'All_Other_Races_2013': 2,
                     'Asian_Population_2013':3, 'Black_Population_2013': 4,'White_Population_2013': 5,
                     'Older_Adult_Population_2013':6, 'Youth_Population_2013':7, 'Age_of_Residents_2013':8, 
                    'Population_Density_2013':9, 'Vacant_Land_2013':10, 
                     'Vacant_Land_Area_2013':11, 'Commercial_Construction_2013':12, 
                     'Commercial_Construction_Permitted_Units_2013':13, 'Commercial_Size_2013':14,
                     'Commercial_Size_Total_2013':15,'Commercial_Building_Age_2013':16,
                     'Impervious_Surface_2013':17,'Impervious_Surface_Area_2013':18, 'Adopt_a_Stream_2013':19,
                     'Adopt_a_Stream_Length_2013':20, 'Pharmacy_Proximity_2013':21,
                     'Pharmacy_Proximate_Units_2013':22,'Housing_Density_2013':23,'Housing_Units_2013':24,
                     'Single_Family_Housing_2013':25, 'Single_Family_Units_2013':26,
                     'Housing_Size_2013':27, 'Housing_Age_2013':28,'New_Residential_2013':29,
                     'New_Residential_Permit_Units_2013':30,'Residential_Renovation_2013':31,
                     'Residential_Renovation_Permit_Units_2013':32,'Foreclosures_2013':33,
                     'Foreclosed_Units_2013':34,'Housing_Violations_2013':35,
                     'Housing_Violations_Total_2013':36,'Street_Connectivity_2013':37,'Transit_Proximity_2013':38,
                     'Transit_Proximate_Units_2013':39,'Violent_Crime_Rate_2013':40,'Property_Crime_Rate_2013':41,
                     'Violent_Crime_Rate_Log2_2013':42,'Property_Crime_Rate_Log2_2013':43,
                    'Violent_Crime_Rate_Class_2013':44,'Property_Crime_Rate_Class_2013':45}

In [140]:
Features_dic_2015 = {'NPA':0, 'Hispanic_Latino_2015': 1,'All_Other_Races_2015': 2,
                     'Asian_Population_2015':3, 'Black_Population_2015': 4,'White_Population_2015': 5,
                     'Older_Adult_Population_2015':6, 'Youth_Population_2015':7, 'Age_of_Residents_2015':8, 
                    'Population_Density_2015':9, 'Vacant_Land_2015':10, 
                     'Vacant_Land_Area_2015':11, 'Commercial_Construction_2015':12, 
                     'Commercial_Construction_Permitted_Units_2015':13, 'Commercial_Size_2015':14,
                     'Commercial_Size_Total_2015':15,'Commercial_Building_Age_2015':16,
                     'Impervious_Surface_2015':17,'Impervious_Surface_Area_2015':18, 'Adopt_a_Stream_2015':19,
                     'Adopt_a_Stream_Length_2015':20, 'Pharmacy_Proximity_2015':21,
                     'Pharmacy_Proximate_Units_2015':22,'Housing_Density_2015':23,'Housing_Units_2015':24,
                     'Single_Family_Housing_2015':25, 'Single_Family_Units_2015':26,
                     'Housing_Size_2015':27, 'Housing_Age_2015':28,'New_Residential_2015':29,
                     'New_Residential_Permit_Units_2015':30,'Residential_Renovation_2015':31,
                     'Residential_Renovation_Permit_Units_2015':32,'Foreclosures_2015':33,
                     'Foreclosed_Units_2015':34,'Housing_Violations_2015':35,
                     'Housing_Violations_Total_2015':36,'Street_Connectivity_2015':37,'Transit_Proximity_2015':38,
                     'Transit_Proximate_Units_2015':39,'Violent_Crime_Rate_2015':40,'Property_Crime_Rate_2015':41,
                     'Violent_Crime_Rate_Log2_2015':42,'Property_Crime_Rate_Log2_2015':43,
                    'Violent_Crime_Rate_Class_2015':44,'Property_Crime_Rate_Class_2015':45}

### change crime rate to classes

In [234]:
# define number of classes
NUM_OF_CLASS = 5

# interval values to retrieve crime rate from crime rate classes
Vcr_max_2011 = max(CM_2011['Violent_Crime_Rate_Log2_2011'])
Vcr_max_2013 = max(CM_2013['Violent_Crime_Rate_Log2_2013'])
Vcr_max_2015 = max(CM_2015['Violent_Crime_Rate_Log2_2015'])
interval_vcr = max(Vcr_max_2011,Vcr_max_2013,Vcr_max_2015)/NUM_OF_CLASS + 0.000001

Pcr_max_2011 = max(CM_2011['Property_Crime_Rate_Log2_2011'])
Pcr_max_2013 = max(CM_2013['Property_Crime_Rate_Log2_2013'])
Pcr_max_2015 = max(CM_2015['Property_Crime_Rate_Log2_2015'])
interval_pcr = max(Pcr_max_2011,Pcr_max_2013,Pcr_max_2015) / NUM_OF_CLASS + 0.000001

# add columns for classes
CM_2011_imputed[44] = 0
CM_2011_imputed[45] = 0

CM_2013_imputed[44] = 0
CM_2013_imputed[45] = 0

CM_2015_imputed[44] = 0
CM_2015_imputed[45] = 0


CM_2011_imputed[Features_dic_2011['Violent_Crime_Rate_Class_2011']] = CM_2011_imputed[Features_dic_2011['Violent_Crime_Rate_Log2_2011']] / interval_vcr
CM_2011_imputed[Features_dic_2011['Property_Crime_Rate_Class_2011']] = CM_2011_imputed[Features_dic_2011['Property_Crime_Rate_Log2_2011']]/ interval_pcr
CM_2011_imputed[[Features_dic_2011['Violent_Crime_Rate_Class_2011'],Features_dic_2011['Property_Crime_Rate_Class_2011']]]=CM_2011_imputed[[Features_dic_2011['Violent_Crime_Rate_Class_2011'],Features_dic_2011['Property_Crime_Rate_Class_2011']]].astype(int)


CM_2013_imputed[Features_dic_2013['Violent_Crime_Rate_Class_2013']] = CM_2013_imputed[Features_dic_2013['Violent_Crime_Rate_Log2_2013']] / interval_vcr
CM_2013_imputed[Features_dic_2013['Property_Crime_Rate_Class_2013']] = CM_2013_imputed[Features_dic_2013['Property_Crime_Rate_Log2_2013']]/ interval_pcr
CM_2013_imputed[[Features_dic_2013['Violent_Crime_Rate_Class_2013'],Features_dic_2013['Property_Crime_Rate_Class_2013']]]=CM_2013_imputed[[Features_dic_2013['Violent_Crime_Rate_Class_2013'],Features_dic_2013['Property_Crime_Rate_Class_2013']]].astype(int)

CM_2015_imputed[Features_dic_2015['Violent_Crime_Rate_Class_2015']] = CM_2015_imputed[Features_dic_2015['Violent_Crime_Rate_Log2_2015']] / interval_vcr
CM_2015_imputed[Features_dic_2015['Property_Crime_Rate_Class_2015']] = CM_2015_imputed[Features_dic_2015['Property_Crime_Rate_Log2_2015']]/ interval_pcr
CM_2015_imputed[[Features_dic_2015['Violent_Crime_Rate_Class_2015'],Features_dic_2015['Property_Crime_Rate_Class_2015']]]=CM_2015_imputed[[Features_dic_2015['Violent_Crime_Rate_Class_2015'],Features_dic_2015['Property_Crime_Rate_Class_2015']]].astype(int)

In [235]:
CM_2011_imputed.head()

,0,1,2,3,4,5,6,7,8,9,...,36,37,38,39,40,41,42,43,44,45
0,2.0,9.2,2.8,1.5,33.7,52.8,8.0,14.0,32.0,5.0,...,7.0,1.17,100.0,1082.0,9.3,120.2,3.217231,6.909293,2,3
1,3.0,2.1,1.9,2.1,10.2,83.7,10.0,13.0,31.0,6.0,...,55.0,1.55,100.0,4468.0,2.0,77.4,1.000000,6.274262,0,2
2,4.0,0.9,0.7,3.5,1.6,93.3,24.0,27.0,43.0,3.0,...,1.0,1.17,100.0,401.0,0.0,13.0,0.000000,3.700440,0,1
3,5.0,2.7,3.5,2.0,83.3,8.6,4.0,36.0,29.0,4.0,...,26.0,1.19,100.0,332.0,21.6,73.0,4.432959,6.189825,3,2
4,6.0,3.8,1.7,1.1,78.6,14.7,9.0,18.0,38.0,4.0,...,35.0,1.30,100.0,825.0,27.5,92.2,4.781360,6.526695,3,2

In [180]:
CM_2013_imputed.head()

,0,1,2,3,4,5,6,7,8,9,...,36,37,38,39,40,41,42,43,44,45
0,2.0,9.2,2.8,1.5,33.7,52.8,8.0,14.0,34.0,5.0,...,13.0,1.15,100.0,1081.0,6.9,32.8,2.786596,5.035624,2,2
1,3.0,2.1,1.9,2.1,10.2,83.7,10.0,13.0,33.0,7.0,...,20.0,1.55,100.0,4746.0,2.2,59.5,1.137504,5.894818,0,2
2,4.0,0.9,0.7,3.5,1.6,93.3,24.0,27.0,45.0,3.0,...,0.0,1.17,100.0,402.0,0.0,9.4,0.000000,3.232661,0,1
3,5.0,2.7,3.5,2.0,83.3,8.6,4.0,36.0,31.0,5.0,...,31.0,1.19,100.0,329.0,24.9,51.1,4.638074,5.675251,3,2
4,6.0,3.8,1.7,1.1,78.6,14.7,9.0,18.0,40.0,4.0,...,54.0,1.30,100.0,820.0,31.0,94.1,4.954196,6.556123,3,2

In [181]:
CM_2015_imputed.head()

,0,1,2,3,4,5,6,7,8,9,...,36,37,38,39,40,41,42,43,44,45
0,2.0,9.2,2.8,1.5,33.7,52.8,8.0,14.0,36.0,5.0,...,10.0,1.20,100.0,1079.0,4.5,31.1,2.169925,4.958843,1,2
1,3.0,2.1,1.9,2.1,10.2,83.7,10.0,13.0,35.0,7.0,...,8.0,1.50,100.0,4752.0,2.1,61.1,1.070389,5.933100,0,2
2,4.0,0.9,0.7,3.5,1.6,93.3,24.0,27.0,47.0,3.0,...,0.0,1.17,94.0,381.0,0.9,19.5,0.900000,4.285402,0,1
3,5.0,2.7,3.5,2.0,83.3,8.6,4.0,36.0,33.0,4.0,...,66.0,1.16,100.0,331.0,18.8,67.1,4.232661,6.068241,3,2
4,6.0,3.8,1.7,1.1,78.6,14.7,9.0,18.0,42.0,4.0,...,54.0,1.30,100.0,817.0,24.4,100.9,4.608809,6.656782,3,3

## Fit Decision Tree

### For 2011 'Violent_Crime_Rate'

In [249]:
y_cls_2011 = CM_2011_imputed[Features_dic_2011['Violent_Crime_Rate_Class_2011']]
x_cls_2011 = CM_2011_imputed.drop([Features_dic_2011['NPA'],Features_dic_2011['Violent_Crime_Rate_2011'],Features_dic_2011['Property_Crime_Rate_2011'],Features_dic_2011['Violent_Crime_Rate_Log2_2011'],Features_dic_2011['Property_Crime_Rate_Log2_2011'],Features_dic_2011['Violent_Crime_Rate_Class_2011'],Features_dic_2011['Property_Crime_Rate_Class_2011']],axis = 1)

y_cls_2011_pc = CM_2011_imputed[Features_dic_2011['Property_Crime_Rate_Class_2011']]

In [237]:
x_cls_2011.head()

,1,2,3,4,5,6,7,8,9,10,...,30,31,32,33,34,35,36,37,38,39
0,9.2,2.8,1.5,33.7,52.8,8.0,14.0,32.0,5.0,4.3,...,0.0,2.67,11.0,1.1,7.0,0.65,7.0,1.17,100.0,1082.0
1,2.1,1.9,2.1,10.2,83.7,10.0,13.0,31.0,6.0,3.2,...,20.0,6.66,77.0,0.7,24.0,1.26,55.0,1.55,100.0,4468.0
2,0.9,0.7,3.5,1.6,93.3,24.0,27.0,43.0,3.0,5.1,...,4.0,8.20,27.0,0.3,1.0,0.25,1.0,1.17,100.0,401.0
3,2.7,3.5,2.0,83.3,8.6,4.0,36.0,29.0,4.0,21.4,...,1.0,1.20,2.0,6.0,11.0,7.83,26.0,1.19,100.0,332.0
4,3.8,1.7,1.1,78.6,14.7,9.0,18.0,38.0,4.0,7.7,...,0.0,1.49,6.0,1.2,7.0,4.24,35.0,1.30,100.0,825.0

In [238]:
y_cls_2011.head()

0    2
1    0
2    0
3    3
4    3
Name: 44, dtype: int64

In [239]:

x_train_2011, x_test_2011, y_train_2011, y_test_2011 = train_test_split(x_cls_2011,y_cls_2011, test_size=0.33, random_state=42)


dt_2011 = DecisionTreeClassifier(random_state = 100, class_weight = 'balanced')
dt_2011.fit(x_train_2011,y_train_2011)
y_pred_2011 = dt_2011.predict(x_test_2011)

In [240]:
target_names = ['very low','low','median','high','very high']
print(classification_report(y_test_2011, y_pred_2011,target_names=target_names))

             precision    recall  f1-score   support

   very low       0.77      0.69      0.73        78
        low       0.43      0.42      0.42        43
     median       0.31      0.33      0.32        24
       high       0.15      0.25      0.19         8
  very high       0.00      0.00      0.00         0

avg / total       0.57      0.54      0.55       153

In [241]:
with open("dt_2011.dot",'w') as f:
    f = tree.export_graphviz(dt_2011,out_file=f)

In [247]:
features = ['Hispanic_Latino_2011','All_Other_Races_2011','Asian_Population_2011',
            'Black_Population_2011','White_Population_2011','Older_Adult_Population_2011',
            'Youth_Population_2011','Age_of_Residents_2011','Population_Density_2011',
            'Vacant_Land_2011','Vacant_Land_Area_2011','Commercial_Construction_2011',
            'Commercial_Construction_Permitted_Units_2011','Commercial_Size_2011',
            'Commercial_Size_Total_2011','Commercial_Building_Age_2011','Impervious_Surface_2011'
            'Impervious_Surface_Area_2011','Adopt_a_Stream_2011	Adopt_a_Stream_Length_2011',
            'Pharmacy_Proximity_2011','Pharmacy_Proximate_Units_2011','Housing_Density_2011',
            'Housing_Units_2011','Single_Family_Housing_2011','Single_Family_Units_2011',
            'Housing_Size_2011','Housing_Age_2011','New_Residential_2011','New_Residential_Permit_Units_2011',
            'Residential_Renovation_2011','Residential_Renovation_Permit_Units_2011','Foreclosures_2011',
            'Foreclosed_Units_2011','Housing_Violations_2011','Housing_Violations_Total_2011','Street_Connectivity_2011',
            'Transit_Proximity_2011','Transit_Proximate_Units_2011']
dot_data_2011 = tree.export_graphviz(dt_2011, out_file=None)

In [243]:
graph = pydotplus.graph_from_dot_data(dot_data_2011)

In [244]:
graph.write_pdf("crime_rate_2011.pdf")

True

### for "Property_Crime_Rate"

In [250]:
x_train_2011_pc, x_test_2011_pc, y_train_2011_pc, y_test_2011_pc = train_test_split(x_cls_2011,y_cls_2011_pc, test_size=0.33, random_state=42)


dt_2011_pc = DecisionTreeClassifier(random_state = 100, class_weight = 'balanced')
dt_2011_pc.fit(x_train_2011_pc,y_train_2011_pc)
y_pred_2011_pc = dt_2011_pc.predict(x_test_2011_pc)

In [251]:
print(classification_report(y_test_2011_pc, y_pred_2011_pc,target_names=target_names))

             precision    recall  f1-score   support

   very low       0.00      0.00      0.00         2
        low       0.70      0.59      0.64        54
     median       0.72      0.72      0.72        88
       high       0.18      0.22      0.20         9
  very high       0.00      0.00      0.00         0

avg / total       0.67      0.63      0.65       153

In [252]:
with open("dt_2011_pc.dot",'w') as f:
    f = tree.export_graphviz(dt_2011_pc,out_file=f)
dot_data_2011_pc = tree.export_graphviz(dt_2011_pc, out_file=None)
graph = pydotplus.graph_from_dot_data(dot_data_2011_pc)
graph.write_pdf("Property_Crime_rate_2011.pdf")

True

### For 2013 'Crime_Rate'

In [253]:
y_cls_2013 = CM_2013_imputed[Features_dic_2013['Violent_Crime_Rate_Class_2013']]
x_cls_2013 = CM_2013_imputed.drop([Features_dic_2013['NPA'],Features_dic_2013['Violent_Crime_Rate_2013'],Features_dic_2013['Property_Crime_Rate_2013'],Features_dic_2013['Violent_Crime_Rate_Log2_2013'],Features_dic_2013['Property_Crime_Rate_Log2_2013'],Features_dic_2013['Violent_Crime_Rate_Class_2013'],Features_dic_2013['Property_Crime_Rate_Class_2013']],axis = 1)

y_cls_2013_pc = CM_2013_imputed[Features_dic_2013['Property_Crime_Rate_Class_2013']]

x_cls_2013.head()

,1,2,3,4,5,6,7,8,9,10,...,30,31,32,33,34,35,36,37,38,39
0,9.2,2.8,1.5,33.7,52.8,8.0,14.0,34.0,5.0,4.3,...,0.0,3.89,16.0,0.9,6.0,1.20,13.0,1.15,100.0,1081.0
1,2.1,1.9,2.1,10.2,83.7,10.0,13.0,33.0,7.0,2.8,...,39.0,9.78,113.0,0.5,17.0,0.42,20.0,1.55,100.0,4746.0
2,0.9,0.7,3.5,1.6,93.3,24.0,27.0,45.0,3.0,5.1,...,1.0,5.77,19.0,0.0,0.0,0.00,0.0,1.17,100.0,402.0
3,2.7,3.5,2.0,83.3,8.6,4.0,36.0,31.0,5.0,21.4,...,0.0,0.60,1.0,0.6,1.0,9.42,31.0,1.19,100.0,329.0
4,3.8,1.7,1.1,78.6,14.7,9.0,18.0,40.0,4.0,7.7,...,0.0,2.73,11.0,1.5,9.0,6.59,54.0,1.30,100.0,820.0

In [254]:
x_train_2013, x_test_2013, y_train_2013, y_test_2013 = train_test_split(x_cls_2013,y_cls_2013, test_size=0.33, random_state=42)


dt_2013 = DecisionTreeClassifier(random_state = 100, class_weight = 'balanced')
dt_2013.fit(x_train_2013,y_train_2013)
y_pred_2013 = dt_2013.predict(x_test_2013)

In [256]:
print(classification_report(y_test_2013, y_pred_2013,target_names=target_names))

             precision    recall  f1-score   support

   very low       0.75      0.66      0.70        87
        low       0.10      0.15      0.12        27
     median       0.37      0.25      0.30        28
       high       0.40      0.60      0.48        10
  very high       0.00      0.00      0.00         1

avg / total       0.54      0.48      0.50       153

In [257]:
with open("dt_2013.dot",'w') as f:
    f = tree.export_graphviz(dt_2013,out_file=f)
dot_data_2013 = tree.export_graphviz(dt_2013, out_file=None)
graph = pydotplus.graph_from_dot_data(dot_data_2013)
graph.write_pdf("Crime_rate_2013.pdf")

True

### For 'Property Crime Rate'

In [258]:
x_train_2013_pc, x_test_2013_pc, y_train_2013_pc, y_test_2013_pc = train_test_split(x_cls_2013,y_cls_2013_pc, test_size=0.33, random_state=42)


dt_2013_pc = DecisionTreeClassifier(random_state = 100, class_weight = 'balanced')
dt_2013_pc.fit(x_train_2013_pc,y_train_2013_pc)
y_pred_2013_pc = dt_2013_pc.predict(x_test_2013_pc)

In [259]:
print(classification_report(y_test_2013_pc, y_pred_2013_pc,target_names=target_names))

             precision    recall  f1-score   support

   very low       0.00      0.00      0.00         7
        low       0.63      0.64      0.64        67
     median       0.62      0.66      0.64        74
       high       0.00      0.00      0.00         5
  very high       0.00      0.00      0.00         0

avg / total       0.58      0.60      0.59       153

In [260]:
with open("dt_2013_pc.dot",'w') as f:
    f = tree.export_graphviz(dt_2013_pc,out_file=f)
dot_data_2013_pc = tree.export_graphviz(dt_2013_pc, out_file=None)
graph = pydotplus.graph_from_dot_data(dot_data_2013_pc)
graph.write_pdf("Property_Crime_rate_2013.pdf")

True

### For 2015 'Crime Rate'

In [261]:
y_cls_2015 = CM_2015_imputed[Features_dic_2015['Violent_Crime_Rate_Class_2015']]
x_cls_2015 = CM_2015_imputed.drop([Features_dic_2015['NPA'],Features_dic_2015['Violent_Crime_Rate_2015'],Features_dic_2015['Property_Crime_Rate_2015'],Features_dic_2015['Violent_Crime_Rate_Log2_2015'],Features_dic_2015['Property_Crime_Rate_Log2_2015'],Features_dic_2015['Violent_Crime_Rate_Class_2015'],Features_dic_2015['Property_Crime_Rate_Class_2015']],axis = 1)

y_cls_2015_pc = CM_2015_imputed[Features_dic_2015['Property_Crime_Rate_Class_2015']]

x_cls_2015.head()

,1,2,3,4,5,6,7,8,9,10,...,30,31,32,33,34,35,36,37,38,39
0,9.2,2.8,1.5,33.7,52.8,8.0,14.0,36.0,5.0,4.3,...,1.0,7.30,30.0,1.1,7.0,0.93,10.0,1.20,100.0,1079.0
1,2.1,1.9,2.1,10.2,83.7,10.0,13.0,35.0,7.0,2.5,...,385.0,10.73,124.0,0.1,4.0,0.17,8.0,1.50,100.0,4752.0
2,0.9,0.7,3.5,1.6,93.3,24.0,27.0,47.0,3.0,5.1,...,6.0,6.99,23.0,0.2,1.0,0.00,0.0,1.17,94.0,381.0
3,2.7,3.5,2.0,83.3,8.6,4.0,36.0,33.0,4.0,21.4,...,0.0,2.39,4.0,2.2,4.0,19.94,66.0,1.16,100.0,331.0
4,3.8,1.7,1.1,78.6,14.7,9.0,18.0,42.0,4.0,7.7,...,0.0,4.46,18.0,1.0,6.0,6.61,54.0,1.30,100.0,817.0

In [262]:
x_train_2015, x_test_2015, y_train_2015, y_test_2015 = train_test_split(x_cls_2015,y_cls_2015, test_size=0.33, random_state=42)


dt_2015 = DecisionTreeClassifier(random_state = 100, class_weight = 'balanced')
dt_2015.fit(x_train_2015,y_train_2015)
y_pred_2015 = dt_2015.predict(x_test_2015)

In [263]:
print(classification_report(y_test_2015, y_pred_2015,target_names=target_names))

             precision    recall  f1-score   support

   very low       0.70      0.66      0.68        87
        low       0.35      0.42      0.38        36
     median       0.26      0.38      0.31        16
       high       0.25      0.08      0.12        13
  very high       0.50      1.00      0.67         1

avg / total       0.53      0.52      0.52       153

In [264]:
with open("dt_2015.dot",'w') as f:
    f = tree.export_graphviz(dt_2015,out_file=f)
dot_data_2015 = tree.export_graphviz(dt_2015, out_file=None)
graph = pydotplus.graph_from_dot_data(dot_data_2015)
graph.write_pdf("Crime_rate_2015.pdf")

True

### For 'Property Crime Rate'

In [266]:
x_train_2015_pc, x_test_2015_pc, y_train_2015_pc, y_test_2015_pc = train_test_split(x_cls_2015,y_cls_2015_pc, test_size=0.33, random_state=42)


dt_2015_pc = DecisionTreeClassifier(random_state = 100, class_weight = 'balanced')
dt_2015_pc.fit(x_train_2015_pc,y_train_2015_pc)
y_pred_2015_pc = dt_2015_pc.predict(x_test_2015_pc)

In [267]:
print(classification_report(y_test_2015_pc, y_pred_2015_pc,target_names=target_names))

             precision    recall  f1-score   support

   very low       0.17      0.18      0.17        11
        low       0.56      0.47      0.51        66
     median       0.59      0.63      0.61        70
       high       0.20      0.33      0.25         6
  very high       0.00      0.00      0.00         0

avg / total       0.53      0.52      0.52       153

In [268]:
with open("dt_2015_pc.dot",'w') as f:
    f = tree.export_graphviz(dt_2015_pc,out_file=f)
dot_data_2015_pc = tree.export_graphviz(dt_2015_pc, out_file=None)
graph = pydotplus.graph_from_dot_data(dot_data_2015_pc)
graph.write_pdf("Property_Crime_rate_2015.pdf")

True